// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApp.Models;

#nullable disable

namespace MyWebApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251201190248_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyWebApp.Models.Orders", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatchBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatchName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("OrdersTable");
                });

            modelBuilder.Entity("MyWebApp.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UsersTable");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("bf9f6fbf-df81-45df-b037-82eaff7aa4d6"),
                            IsOnline = false,
                            UserEmail = "admin@gmail.com",
                            UserName = "admin",
                            UserPassword = "admin2627"
                        },
                        new
                        {
                            UserId = new Guid("16e762fa-6db5-40fe-9f94-049f475afc01"),
                            IsOnline = false,
                            UserEmail = "random@gmail.com",
                            UserName = "Random",
                            UserPassword = "random1234"
                        });
                });

            modelBuilder.Entity("MyWebApp.Models.Watch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WatchBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WatchesTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("843f7c4d-e699-491b-a3e9-045b51a25c70"),
                            Img = "https://d2j6dbq0eux0bg.cloudfront.net/images/38270005/4079824799.jpg",
                            Price = 12525m,
                            WatchBrand = "Rolex",
                            WatchName = "Silver Index Fluted Yellow Gold Leather 18238"
                        },
                        new
                        {
                            Id = new Guid("60c5951c-1c33-4184-8808-07e2a396d1dc"),
                            Img = "https://img.chrono24.com/images/uhren/42214924-sc9belurrolnws8n76a18bwe-ExtraLarge.jpg",
                            Price = 49999m,
                            WatchBrand = "Audemars Piguet",
                            WatchName = "26315ST Silver & Blue Dial Mens Watch Box Papers"
                        },
                        new
                        {
                            Id = new Guid("b720e0ed-5b5d-4aaf-97dd-5d6defb83b1a"),
                            Img = "https://s3.us-east-1.amazonaws.com/ISHOWIMAGES/ROLEX+V7/wp/model_gallery_assets_portrait/Slide4_portrait/m126506-0001.webp",
                            Price = 28000m,
                            WatchBrand = "Rolex",
                            WatchName = "Sport Daytona 16518 Full set Pre-owned 1997"
                        },
                        new
                        {
                            Id = new Guid("2e0592bd-a5a4-485e-992d-9985ac0e3b57"),
                            Img = "https://img.chrono24.com/images/uhren/43258204-pk3j42yayatax2wodailsezm-ExtraLarge.jpg",
                            Price = 15999m,
                            WatchBrand = "A. Lange & Söhne",
                            WatchName = "Thin"
                        },
                        new
                        {
                            Id = new Guid("01706492-d963-4c7f-a069-9d80f42e203f"),
                            Img = "https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-diver-300m-co-axial-master-chronometer-42-mm-21032422001005-2b286f.png?w=700",
                            Price = 337m,
                            WatchBrand = "Omega",
                            WatchName = "Seamaster Diver 300M"
                        },
                        new
                        {
                            Id = new Guid("5a2ec16c-d2a3-4023-a8bc-aaf12f6b0017"),
                            Img = "https://img.chrono24.com/images/uhren/42798797-ultc6577p1gbjwgwgy79ogrh-ExtraLarge.jpg",
                            Price = 2450m,
                            WatchBrand = "Ernest Borel",
                            WatchName = "Triple Calendar Moon Phase Indicates week day month date and accurate moon phase"
                        },
                        new
                        {
                            Id = new Guid("3f2b06b8-aebb-4866-a194-c93bd381f11b"),
                            Img = "https://cdn.saatvesaat.com.tr/media/catalog/product/b/5/b5a02869a055070e6ed199509d879f19a4dd08cbeb488683f231fe5148fda3e0.jpeg",
                            Price = 8770m,
                            WatchBrand = "WELDER",
                            WatchName = "Welder WRC407 45 mm Erkek Kol Saati"
                        },
                        new
                        {
                            Id = new Guid("58d1f733-7a74-4ec8-afcc-d67139db2846"),
                            Img = "https://i.ebayimg.com/images/g/IwEAAeSwQaJoyv-a/s-l1200.jpg",
                            Price = 6895m,
                            WatchBrand = "Cartier",
                            WatchName = "De Cartier Large Silver Dial Stainless Steel WSSA0018 4072"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
