// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApp.Models;

#nullable disable

namespace MyWebApp.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyWebApp.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserOrders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UsersTable");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("bf9f6fbf-df81-45df-b037-82eaff7aa4d6"),
                            IsOnline = false,
                            UserEmail = "admin@gmail.com",
                            UserName = "admin",
                            UserPassword = "admin2627"
                        },
                        new
                        {
                            UserId = new Guid("f30379bd-ee19-4582-a4ed-976841d89390"),
                            IsOnline = false,
                            UserEmail = "mfurkantelli@gmail.com",
                            UserName = "Furkan",
                            UserPassword = "26278367"
                        });
                });

            modelBuilder.Entity("MyWebApp.Models.Watch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WatchBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WatchesTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("843f7c4d-e699-491b-a3e9-045b51a25c70"),
                            Img = "https://d2j6dbq0eux0bg.cloudfront.net/images/38270005/4079824799.jpg",
                            Price = 12525m,
                            WatchBrand = "Rolex",
                            WatchName = "Silver Index Fluted Yellow Gold Leather 18238"
                        },
                        new
                        {
                            Id = new Guid("60c5951c-1c33-4184-8808-07e2a396d1dc"),
                            Img = "https://img.chrono24.com/images/uhren/42214924-sc9belurrolnws8n76a18bwe-ExtraLarge.jpg",
                            Price = 49999m,
                            WatchBrand = "Audemars Piguet",
                            WatchName = "26315ST Silver & Blue Dial Mens Watch Box Papers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
